max_process_limit: false
cpu_usage: 69
gpu_usage: 0
generalize: true
netlist_folder_name: netlist_template_FC_SSF_N65
specs_folder_name: sampled_specs_FC_SSF
config_folder_name: config_FC_SSF_N65_C
run_folder_name: run_test
sim_output: false
init_method: half
dc_check: true
restore_checkpoint: false
checkpoint_path: None
train_iterations: 2000